function [resultsBW, resultsBG, resultsBY, resultsRG, resultsRY ] = rh_getResults()
    %RH_GETRESULTS Function to get the results produced by rh_analysis for all
    %of the raw data. Returns results for all five conditions for all 4
    %participants

    %% START
    trainCodesPad = 'C:\users\Robin\Downloads\Data\mgold_61_6521_flip_balanced.mat';

    %% BLACK_WHITE
    disp('BLACK_WHITE')
    resultsBW(1) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S01\black_white_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S01\black_white_1\trainlabels.mat', ...
        trainCodesPad); 
    resultsBW(2) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S02\black_white_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S02\black_white_1\trainlabels.mat', ...
        trainCodesPad); 
    resultsBW(3) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S03\black_white_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S03\black_white_1\trainlabels.mat', ...
        trainCodesPad); 
    resultsBW(4) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S04\black_white_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S04\black_white_1\trainlabels.mat', ...
        trainCodesPad); 

    %% BLUE_GREEN
    disp('BLUE_GREEN')
    resultsBG(1) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S01\blue_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S01\blue_green_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsBG(2) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S02\blue_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S02\blue_green_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsBG(3) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S03\blue_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S03\blue_green_1\trainlabels.mat', ...
        trainCodesPad); 
    resultsBG(4) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S04\blue_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S04\blue_green_1\trainlabels.mat', ...
        trainCodesPad);  

    %% BLUE_YELLOW
    disp('BLUE_YELLOW')
    resultsBY(1) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S01\blue_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S01\blue_yellow_1\trainlabels.mat', ...
        trainCodesPad); 
    resultsBY(2) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S02\blue_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S02\blue_yellow_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsBY(3) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S03\blue_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S03\blue_yellow_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsBY(4) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S04\blue_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S04\blue_yellow_1\trainlabels.mat', ...
        trainCodesPad); 

    %% RED_YELLOW
    disp('RED_YELLOW')
    resultsRY(1) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S01\red_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S01\red_yellow_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsRY(2) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S02\red_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S02\red_yellow_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsRY(3) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S03\red_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S03\red_yellow_1\trainlabels.mat', ...
        trainCodesPad); 
    resultsRY(4) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S04\red_yellow_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S04\red_yellow_1\trainlabels.mat', ...
        trainCodesPad);  

    %% RED_GREEN
    disp('RED_GREEN')
    resultsRG(1) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S01\red_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S01\red_green_1\trainlabels.mat', ...
        trainCodesPad); 
    resultsRG(2) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S02\red_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S02\red_green_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsRG(3) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S03\red_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S03\red_green_1\trainlabels.mat', ...
        trainCodesPad);  
    resultsRG(4) = rh_analysis(...
        'C:\users\Robin\Downloads\Data\S04\red_green_1\traintrials.mat', ...
        'C:\users\Robin\Downloads\Data\S04\red_green_1\trainlabels.mat', ...
        trainCodesPad);  
end

